# 1. Set the output file type to GIF animation
set term gif animate delay 5 size 800,800
set output 'swimmer_simulation.gif'

# 2. Set up the visual "Box"
set xrange [-110:110]
set yrange [-110:110]
set size ratio 1
set grid
set title "Taylor Line Swarm in Circular Confinement"

# 3. Draw the Rigid Boundary (FIXED LINE)
# fs empty = make inside transparent
# border lc rgb "black" = make the outline black
set object 1 circle at 0,0 size 100 fs empty border lc rgb "black" lw 2

# 4. Define line styles for the swimmers
# pt 7 = filled circle, ps 0.4 = point size
set style line 1 lc rgb "blue" pt 7 ps 0.4 lw 1

# 5. Animation Loop
# Ensure the upper limit (200) matches the number of files generated by your C++ code
do for [i=0:200] {
    filename = sprintf('file%d.txt', i)

    # Check if file exists to prevent errors
    system_check = sprintf("test -f '%s' && echo 1 || echo 0", filename)
    exists = system(system_check)

    if (exists eq "1") {
        plot filename using 1:2 with linespoints ls 1 notitle
    }
}
