# 1. Set the output file type to GIF animation
set term gif animate delay 5 size 800,800
set output 'swimmer_simulation.gif'

# 2. Set up the dynamic visual "Box" based perfectly on R_val
box_size = R_val + 15
set xrange [-box_size:box_size]
set yrange [-box_size:box_size]
set size ratio 1
set grid
set title "Taylor Line Swarm in Circular Confinement"

# 3. Draw the Rigid Boundary (INITIAL FIXED LINE - will update dynamically)
# fs empty = make inside transparent
# border lc rgb "black" = make the outline black
set object 1 circle at 0,0 size R_val fs empty border lc rgb "black" lw 2

# 4. Define line styles for the swimmers
# pt 7 = filled circle, ps 0.4 = point size
set style line 1 lc rgb "blue" pt 7 ps 0.4 lw 1

# 5. Animation Loop
# Ensure the upper limit matches the number of files generated by your C++ code
do for [i=0:50000] {
    filename = sprintf('./data/file%d.txt', i)

    # Check if file exists to prevent errors
    system_check = sprintf("test -f '%s' && echo 1 || echo 0", filename)
    exists = system(system_check)

    if (exists eq "1") {
        # Dynamically extract current R from the first line: "# R_val <value>"
        cmd = sprintf("head -n 1 '%s' | awk '{print $3}'", filename)
        current_R = system(cmd) + 0.0
        
        # Update the rigid boundary object visually
        set object 1 circle at 0,0 size current_R fs empty border lc rgb "black" lw 2
        
        plot filename using 1:2 with linespoints ls 1 notitle
    }
}
